repos:
  - repo: https://github.com/python/black
    rev: 23.10.0
    hooks:
    - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.1"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

