dependencies:
  - gdal
  - httpx
  - pandas
  # database
  - postgresql
  - psycopg
  - pydantic
  - pygrib
  # sigh, need github main build
  # - pyiem >=1.20.0
  - pytest
  - pytest-cov
  - rasterio
  - seaborn
  # For testing
  - werkzeug
